### ISSUE TITLE
Feature Request: Add some api method for use with third party module

### ISSUE THREAD

**Issue by p4535992** [acd-jake/acd-talking-actors#32]
Can you add some api (game.modules.get(“acd-talking-actors”).api is the standard path) to be able to integrate your module into other modules ?

Specifically the TextToSpeech function, but also whatever method you think would be useful for integration with other modules.

**Comment by acd-jake** [comment]
Hello, 
I have actually already thought about this.

I will therefore implement the api accordingly in one of the next releases.

I think that in addition to the "textToSpeech" function, the "getVoiceIdAndSettingsFromActor" function could also be integrated directly into the API. This allows you to query the voice settings for an actor and, for example, change them depending on the situation before passing them on to "textToSpeech".

In addition, the function "tryGetSpeakerActorForNarratingActor" would make sense for the api in order to get the configured narrating actor.

I think these functions can be used to implement the majority of useful scenarios.
